Remove disabled packages
feross/standard-packages pull request #35
Opened 2019-09-14 08:06 UTC by sonicdoe

Removes all currently disabled packages from `test.json`. See https://github.com/standard/standard-packages/pull/32#issuecomment-530173455.

2019-09-14 20:51 UTC, feross requested changes
This generally looks good, but I'd like to keep a few of the repos you removed since they are currently passing.

2019-09-14 20:51 UTC, feross commented on test.json
> -    "disable": true
This package is on standard 14.1.0 and it is now passing. Let's keep it in the test suite and not mark it as disabled anymore.

Pro-tip: You can run `npm run test -- --disabled` to run the test suite against repos marked as disabled. If any of them pass, they can be re-enabled.

2019-09-14 20:51 UTC, feross commented on test.json
> -    "disable": true
Let's keep this one. It now passes, plus they're on standard 13 and they seem to be keeping up to date (14 only came out a month ago).

2019-09-14 20:51 UTC, feross commented on test.json
> -    "disable": true
This package is on standard 14.2.0. Leave it.

2019-09-14 20:51 UTC, feross commented on test.json
> -    "disable": true
Leave this. It's passing now.

2019-09-14 20:51 UTC, feross commented on test.json
> -    "disable": true
Leave this. It's passing now.

2019-09-14 20:51 UTC, feross commented on test.json
> -    "disable": true
Leave this. Passing now.

2019-09-14 20:51 UTC, feross commented on test.json
> -    "disable": true
Leave this. Passing now.

2019-09-16 16:32 UTC, sonicdoe commented
I’ve rebased onto `master` now that #36 is merged. This also addresses all requested changes.

2019-09-16 22:19 UTC, feross approved these changes
LGTM, thanks for all these updates :)

2019-09-16 22:20 UTC, merged